@extends('frontend.layout.app')
@section('content')

<div class="container">
<section data-id="facc8a8" data-element_type="section">
<div>
<div data-id="8f0340c" data-element_type="column">
<div>
<div data-id="f5d5959" data-element_type="widget" data-widget_type="heading.default">
<div>
      @if (Session('error'))
                                <span style="color:red; font-weight: 600">{{ Session('error') }}</span>

                            @endif
<h2 class="text-center">STOCK BENEFITS FINANCIAL SERVICES - CLIENT SERVICE AGREEMENT</h2>
</div>
</div>
</div>
</div>
</div>
</section>
<section data-id="1794dd78" data-element_type="section">
<div>
<div data-id="145c2be7" data-element_type="column">
<div>
<div data-id="702dd8e7" data-element_type="widget" data-widget_type="text-editor.default">
<div>
<p>Agreement Mr. Amit Guruh Sachdeva (Proprietor STOCK BENEFITS FINANCIAL SERVICES) SEBI Registered Research Analyst No. INH100005190 &amp; Investment Advisors Registration No. INA100007745 Advisory Services Agreement</p>
<p><strong>THIS INVESTMENT ADVISORY SERVICES AGREEMENT&nbsp;</strong>(the &ldquo;Agreement&rdquo;) BETWEEN Client (Proprietor STOCK BENEFITS FINANCIAL SERVICES), a registered investment advisor with SEBI Registration No. INH100005190 &amp; INA100007745 having an office on the 1502, Kamdhenu Building, Sector 14, Kharghar Navi Mumbai, Maharashtra - 410210 (hereinafter referred to as the &ldquo;INVESTMENT ADVISOR&rdquo; which expression shall unless excluded by or repugnant to the context, be deemed to include its administrators and permitted assigns) of the FIRST PART And Client (hereinafter referred to as the &ldquo;CLIENT &rdquo; which expression shall unless it be repugnant to the context or be deemed to mean and include, its administrators &amp; permitted assigns) of the SECOND PART;</p>
<p>Both INVESTMENT ADVISOR and the CLIENT shall also hereinafter individually referred to as Party &amp; collectively as Parties. Whereas the CLIENT is desirous of availing the advisory services in respect of the analysis of the investment portfolio from the Investment Advisor on the terms &amp; conditions as described hereinafter.</p>
<ol>
<li><strong>APPOINTMENT OF THE INVESTMENT ADVISOR:</strong></li>
<li>In accordance with the applicable laws, the client hereby appoints, entirely at his / her / its risk, the Investment Advisor to provide the required services in accordance with the terms and conditions of the agreement as mandated under Regulation19(1)(d) of the Securities and Exchange Board of India (Investment Advisors) Regulations, 2013.</li>
<li><strong>CONSENT OF THE CLIENT</strong>&nbsp;&ldquo;I / We have read and understood the terms and conditions of Investment Advisory services provided by the Investment Advisor, Disclosure document along with the fee structure and mechanism for charging and payment of a fee.&rdquo; &ldquo;Based on our written request to the Investment Advisor, an opportunity was provided by the Investment Advisor to ask questions and interact with &lsquo;person(s) associated with the investment advice&rdquo;.</li>
<li><strong>DECLARATION FROM THE INVESTMENT ADVISOR</strong>&nbsp;shall neither render any investment advice nor charge any fee until the client has signed this agreement. The investment Advisor shall not manage funds and securities on behalf of the client and it shall only receive such sums of money from the client as are necessary to discharge the client&rsquo;s liability towards fees owed to the Investment Advisor.</li>
</ol>
<p>Investment Advisor shall not, in the course of performing its services to the client, hold out any investment advice implying any assured returns or minimum returns or target return or percentage accuracy or service provision till achievement of target returns or any other nomenclature that gives the impression to the client that the investment advice is risk-free and/or not susceptible to market risks and or that it can generate returns with any level of assurance.</p>
<ol>
<li><strong>FEES SPECIFIED UNDER INVESTMENT ADVISOR REGULATIONS AND RELEVANT CIRCULARS ISSUED THEREUNDER&nbsp;</strong>Regulation 15 A of the amended IA Regulations provide that Investment Advisors shall be entitled to charge fees from a client in the manner as specified by SEBI, accordingly Investment Advisors shall charge fees from the clients in either of the two modes: A. Assets Under Advice (AUA) mode</li>
<li>The maximum fees that may be charged under this mode shall not exceed 2.5 percent of AUA per annum per client across all services offered by IA. b. IA shall be required to demonstrate AUA with supporting documents like Demat statements, unit statements, etc. of the client. c. Any portion of AUA held by the client under any pre-existing distribution arrangement with any entity shall be deducted from AUA for the purpose of charging a fee by the IA. B. Fixed fee mode The maximum fees that may be charged under this mode shall not exceed INR 1,25,000 per annum per client across all services offered by IA &amp; as per Fees of Service delivered under SEBI RA Regulations.. In case &ldquo;family of the client&rdquo; is reckoned as a single client, the fee as referred above shall be charged per &ldquo;family of the client&rdquo;.</li>
<li>IA shall charge fees from a client under any one mode i.e. (A) or (B) on an annual basis. The change of mode shall be effected only after 12 months of onboarding/last change of mode.</li>
<li>If agreed by the client, IA may charge fees in advance. However, such advance shall not exceed fees for 2 quarters or Subject to Client Discretion.</li>
<li>In the event of premature termination of the IA services in terms of the agreement, the client shall be refunded the fees for the unexpired period. However, IA may retain a maximum breakage fee of not greater than a one-quarter fee. Research Analysis Services holds its fee structure as per service delivered.</li>
<li><strong>FEES APPLICABLE TO THE CLIENT AND BILLING</strong>&nbsp;Details of Fees to be charged are the following:</li>
<li>Product / Service subscribed: Product/ Service Subscribed Index Option Number of Calls 01-02 Calls per day Type Intraday Only Delivery Via SMS</li>
<li>The quantum and manner of payment of fees for investment advice rendered. Amount (Quantum) Mode of Payment 0(In Words of Rupees Rupees Only) NEFT/ RTGS/IMPS/UPI</li>
<li>Fee modalities and periodicity, by attaching a detailed fee schedule to the agreement; Fees accepted strictly by account payee crossed cheques / demand draft or by way of direct credit into my bank account through NEFT/ RTGS/IMPS/UPI. Cash deposits are not accepted for any of the service provided.</li>
<li>Illustration(s) on how the fee will be determined; 1. Fixed fee mode based on selected product</li>
<li>Whether payment to be made in advance; 1. Fees are payable in advance at the time of onboarding, in case the product is having a validity of fewer than 6 months. 2. Fees of two-quarters payable in advance at the time of onboarding, in case the product is having a validity of more than 6 months, the next payment will fall due on completion of 6 months</li>
<li>type of documents evidencing receipt of payment of fee; -Payment Receipt.</li>
<li>Periodicity of billing with clear date and service period. S. No. Periodicity of billing with clear date Service Package Service Period 1 10th May 2022 Index Option 0 Days The payment of fees shall be through any mode which shows traceability of funds. Such modes may include account payee crossed cheque/ Demand Drafts or by way of direct credit to the bank accounts through NEFT/ RTGS/ IMPS/ UPI or any other mode specified by SEBI from time to time.</li>
</ol>
<p>However, the fees shall not be in cash. Investment Advisor &amp; Research Analyst shall receive all considerations by way of remuneration or compensation or in any other form from the client only and not from any person other than the client being advised, in respect of the underlying securities or investment products for which the advice is or to be provided.</p>
<p><strong>SCOPE OF SERVICE</strong></p>
<ol>
<li>Investment Advisor &amp; Research Analyst may provide some or all of the following services to the Client:</li>
</ol>
<p>Assist in articulating the family goals &amp; objectives. Assist in assessing the risk profile. Develop an Investment Policy Statement based on your goals and risk profile. Develop investment recommendations based on goals &amp; risk profile and assist in implementing these recommendations. Provide advice with respect to the investment in equity, mutual funds, insurance, commodities and other financial assets, as needed, and assist in implementing recommendations. Provide advice and recommendations in any other areas of financial planning in which Advisor or Client identifies a need.</p>
<p><strong>DUTIES &amp; FUNCTIONS OF THE INVESTMENT ADVISOR &amp; RESEARCH ANALYST</strong></p>
<p>Investment Advisor &amp; Research Analyst shall provide Investment Advisory Services to the Client during the term of this Agreement on investment in all financial/investment products under all regulated authorities as is permitted under applicable laws and regulations governing Investment Advisor &amp; the financial industry. The services rendered by the Investment Advisor are non-binding non-recourse advisory in nature and the final decision on the type of instruments; the proportion of exposure and tenure of the investments shall be taken by the Client at its discretion. The investment Advisor shall act in a fiduciary capacity as one of the advisors to the Client with respect to managing its investment-related portfolio holistically &amp; will be providing all back-end support services. The investment Advisor shall act in a bonafide manner for the benefit and the interest of the Client. The investment Advisor shall be in compliance with the SEBI (Investment Advisors) Regulations, 2013 and its amendments, rules, circulars, and notifications. The investment Advisor shall be in compliance with the eligibility criteria as specified under the IA Regulations at all times. Pursuant to the SEBI (INVESTMENT ADVISORS) REGULATIONS, 2013 guidelines with respect to Risk Profiling and Suitability Assessment, Investment Advisor shall conduct proper risk profiling and risk assessment for each of the clients. As per risk analysis, risk capacity, risk aversion &amp; client requirement, the Investment Advisor needs to ensure that correct product/service as per client risk tolerance capacity is being offered, which is suitable for client. Investment Advisor shall provide reports to clients on potential and current investments if requested. Investment Advisor shall maintain client-wise KYC, advice, risk assessment, analysis reports of investment advice and suitability, terms and conditions document, rationale of advice, related books of accounts and a register containing list of clients along with dated investment advice in compliance with the SEBI (Investment Advisors) Regulations, 2013. Investment Advisor shall get annual compliance audit conducted as per the SEBI (Investment Advisors) Regulations, 2013. Investment Advisor undertakes to abide by the Code of Conduct as specified in the Third Schedule of the SEBI (Investment Advisors) Regulations, 2013. Investment Advisor shall not receive any consideration in any form, if the client desires to avail the services of intermediary recommended by Investment Advisor.</p>
<p><strong>INVESTMENT OBJECTIVE AND GUIDELINES&nbsp;</strong>Investment Advisor &amp; Research Analyst (RA) would provide investment advice with respect to investment in equity &amp; Derivatives. Investment Advisor undertakes to recommend direct implementation of advice i.e. Demat Accounts or as the case may be. Investment Advisor shall provide investment advice based on the risk profiling conducted for the client, total budgeted investment amount of the client and time period for deployment as informed by the client. Investment Advisor shall communicate the tax related aspects pertaining to investment advice and as applicable on the investment advisor&rsquo;s fee, if any.</p>
<p><strong>RISK FACTORS&nbsp;</strong>Investments in securities are subject to market risks and there is no assurance or guarantee that the objective of the investments will be achieved; Past performance of the investment advisor does not indicate its future performance. The performance of the investments/products may be affected by changes in Government policies, general levels of interest rates and risks associated with trading volumes, liquidity and settlement systems in equity and debt markets. Investments in the products which the Clients have opted are subject to wide range of risks which inter alia also include but not limited to economic slowdown, volatility &amp; illiquidity of the stocks, poor corporate performance, economic policies, changes of Government and its policies, acts of God, acts of war, civil disturbance, sovereign action and /or such other acts/ circumstance beyond the control of Investment Advisor or any of its Associates. The names of the products/nature of investments do not in any manner indicate their prospects or returns. The performance in the equity may be adversely affected by the performance of individual companies, changes in the market place and industry specific and macro-economic factors. Investments in debt instruments and other fixed income securities are subject to default risk, liquidity risk and interest rate risk. Interest rate risk results from changes in demand and supply for money and other macroeconomic factors and creates price changes in the value of the debt instruments. Under NO Conditions the Investment Advisor OR Research Analyst OR any member associated with the Firm can be held personally or cumulatively responsible for any financial loss directly or Indirectly incurred in the stock market. The Advisor has the responsibility to give the best research and advise with the intention to generate returns to the client subject to inherent risk of the stock market. There is no assurance or guarantee of returns or capital safety of the client due to unavoidable market volatility or unpredictable high irrational moves. The client accepts the nature of business risk and capital risk involved in the stock market &amp; cannot held responsible to IA OR RA OR Employees of the firm for any unprecedent loss of returns or capital involved in trading &amp; Investment Activites.</p>
<p><strong>VALIDITY OF ADVISORY SERVICES</strong>&nbsp;The validity of this agreement starts from the date of signing and will continue to be in force till any of the parties terminate it by giving 1 months&rsquo; notice period or as per tenure mentioned &amp; agreed upon.</p>
<p><strong>TERMINATION&nbsp;</strong>This Agreement may be terminated under the following circumstances, namely- (a) Voluntary / mandatory termination by the Investment Advisor. (b) Voluntary / mandatory termination by the client. (c) Suspension/Cancellation of registration of Investment Advisor by SEBI. (d) Any other action taken by other regulatory body/ Government authority. In case of a voluntary termination of the agreement, the client would be required to give a 30 days prior written notice while the Investment Advisor would be required to give a 30 days prior written notice. In case of suspension of the certificate of registration of the IA, the client may terminate the agreement.</p>
<p><strong>IMPLICATIONS OF AMENDMENTS AND TERMINATION</strong>&nbsp;Notwithstanding any such termination, all rights, liabilities and obligations of the parties arising out of or in respect of transactions entered into prior to the termination of this relationship shall continue to subsist and vest in/be binding on the respective parties or his/its respective heirs, executors, administrators, legal representatives or successors, as the case may be; In case the clients are not satisfied with the services being provided by the investment advisor and want to terminate/ stop Investment Advisory services or the investment advisor is unable to provide Investment Advisory services, either party shall have a right to terminate Investment Advisory relationship at any time subject to refund of advisory fee after deducting one quarters fee &amp; taxes in case termination is initiated by the clients and refund of the proportionate post Gst of advisory fee in case termination is initiated by Investment Advisor. The Investment Advisor would provide transition support, if requested, to the client in the event of termination.</p>
<p><strong>RELATIONSHIP WITH RELATED PARTIES:</strong>&nbsp;Investment Advisor is carrying on its activities independently, at an arms-length basis from all other activities Investment Advisor does not have any conflict of interest of the investment advisory activities with its relationship with related parties, such conflict of interest shall be disclosed to the client as and when they arise.</p>
<p><strong>INVESTMENT ADVISOR ENGAGED IN OTHER ACTIVITIES</strong>&nbsp;Investment Advisor maintains an arms-length relationship between its activities as an investment advisor and other activities and shall ensure that this arm&rsquo;s length relationship would be maintained throughout the tenure of advisory service Investment Advisor shall not provide any distribution services. Family of an individual Investment Advisor shall not provide distribution services to the client advised by the individual Investment Advisor, for securities and investment products. Investment advisor shall not provide investment advisory services, for securities and investment products, to a client who is receiving distribution services from other family members; REPRESENTATION TO CLIENT Investment Advisor shall ensure that it will take all consents and permissions from the client prior to undertaking any actions in relation to the securities or investment product advised by the investment advisor.</p>
<p><strong>NO RIGHT TO SEEK POWER OF ATTORNEY</strong>&nbsp;The Investment Advisor shall not seek any power of attorney or authorizations from its clients for implementation of investment advice.</p>
<p><strong>NO CONFLICT OF INTEREST&nbsp;</strong>Investment Advisor does not have any conflict of interest of the investment advisory activities, such conflict of interest shall be disclosed to the client as and when they arise. Investment advisor shall not derive any direct or indirect benefit out of the client&rsquo;s securities/investment products.</p>
<p><strong>MAINTENANCE OF ACCOUNTS AND CONFIDENTIALITY</strong>&nbsp;Investment Advisor shall be responsible for maintenance of client accounts and data as mandated under the SEBI (Investment Advisors) Regulations, 2013. Investment Advisor shall not divulge any confidential information about its client, which has come to its knowledge, without taking prior permission of its client, except where such disclosures are required to be made in compliance with any law for the time being in force.</p>
<p><strong>LIABILITY OF INVESTMENT ADVISOR</strong>&nbsp;Investment Advisor shall not incur any personal or cumulative liability by reason of any loss, which a client may suffer by reason or any depletion in the value of the assets under advice, which may result by reason of fluctuation in asset value, or by reason of non-performance or under-performance of the securities/funds or any other market conditions.</p>
<p><strong>REPRESENTATIONS AND COVENANTS</strong>&nbsp;The Name of Investment Advisor - Mr. Amit Guruh Sachdeva, Contact No. - 9307714577, Email id - &nbsp;amitguruhsachdeva@yahoo.com&nbsp;Certification Qualification PGDBM (Finance).&nbsp;1. NISM-Series-X-A: Investment Advisor (Level 1) Certification 2. NISM-Series-X-B: Investment Advisor (Level 2) Certification PGDBM Proprietor is Certification Qualifications Investment Advisor is registered with SEBI as Investment Advisor with Registration No. INA100007745.</p>
<p><strong>SETTLEMENT OF DISPUTES AND PROVISION FOR ARBITRATION&nbsp;</strong>No suit, prosecution or another legal proceeding shall lie against the Investment advisor for any damage caused or likely to be caused by anything which is done in good faith or intended to be done under the provisions of the Securities and Exchange Board of India (Investment Advisors) Regulations, 2013. This Agreement is subject to the rules and regulations as are or may be framed/ issued by the Central Government, the Reserve Bank of India (RBI), SEBI, and/or any other competent authority, from time to time. All disputes, differences, claims, and questions whatsoever arising from this Agreement between the Client and Investment Advisor and/or their respective representatives touching these presents shall be in accordance with and subject to the provisions of The Arbitration and Conciliation Act, 1996, or any statutory modification or re-enactment thereof for the time being in force. Such arbitration proceedings shall be held at Indore and the language of the arbitration will be English.</p>
<p><strong>ADHERENCE TO GRIEVANCE REDRESSAL TIMELINES</strong>&nbsp;Investment Advisor shall be responsible to resolve the grievances within the timelines specified under SEBI circulars.</p>
<p><strong>SEVERABILITY</strong>&nbsp;If any provision of this Agreement shall be held or made invalid by a court decision, statute, rule, or otherwise, the remainder of this Agreement shall not be affected thereby</p>
<p><strong>FORCE MAJEURE</strong>&nbsp;The Investment Advisor shall not be liable for delays or errors occurring by reason of circumstances beyond its control, including but not limited to acts of civil or military authority, national emergencies, work stoppages, fire, flood, catastrophe, acts of God, insurrection, war, riot, or failure of communication or power supply. In the event of equipment breakdowns beyond its control, the Investment Advisor shall take reasonable steps to minimize service interruptions but shall have no liability with respect thereto.</p>
<p><strong>MISCELLANEOUS</strong>&nbsp;Each party agrees to perform such further actions and execute such further agreements as are necessary to effectuate the purposes hereof Client shall go through the Disclosure Document and Disclaimer before subscribing to the services of the Investment Advisor to make an informed decision for engaging Investment Advisor before investing. The client shall complete the risk profiling questionnaire before subscribing to the product/services suitable to the client Agreed and Accepted</p>
<p>(Proprietor STOCK BENEFITS FINANCIAL SERVICES) Mr. Amit Guruh Sachdeva</p>
<ol>
<li>Moderate risk investor &ndash; This type of investor is able to accept investment loss occasionally and is willing to take the small risk associated with the market. The services recommended will be in equity cash segment..</li>
<li>High-risk investor &ndash; This type of investor is keen on opportunities to generate a high return and is able to accept substantial risk and can accept quite high investment loss. (They are traders in nature and look for speculative gains opportunities in stock markets and are exposed to derivatives F &amp; O Tradings.)</li>
</ol>
<p>So it is our responsibility to inform and explain each and everything to the client about the risk involved in trading and investment in stock markets which can help substantial loss to the tune of erosion of capital involved. Our model of advisory is fee-based which does not include any commission or remuneration, referral fee, and any other payment from any third party or person. The main purpose of preparing this report is to complete the KYC, Risk Profiling, and &lsquo;Client&rsquo;s service provider agreement&rsquo;.</p>
<p>The suitability of an investment for a particular person is the very heart of the investment process. This is a fundamental concept both from a legal perspective and in terms of putting investors&rsquo; money to work sensibly and prudently. As per Securities Exchange Board of India (SEBI), Investment Advisor Regulations 2013, Regulation 17 gives details about the point which are mentioned in the suitability report and in regulation 19(c) the suitability assessment of advice being provided to the client For Client PARTICULARS DETAILS NAME OF CLIENT &hellip; DATE OF BIRTH &hellip; RISK SCORE &hellip; RISK PROFILE High &ndash; Preferred Service Future, Option, Commodity SERVICE Index Option RISK NATURE High &ndash; Preferred Service Future, Option, Commodity Risk Bearing Capacity Service Details</p>
<p><strong>PARTICULARS DETAILS NAME OF SERVICE Index Option SUBJECT MATTER</strong></p>
<p>The advice and recommendation are based on fundamental and technical analysis. FRFREQUENCY OFERVICE In this service, We provide Intraday plus holding Recommendations MARKET NSE RISK NATURE High &ndash; Preferred Service Future, Option, Commodity Risk Past performance is not evidence for future success, but in every field, the benchmark is important for comparison. Past performance indicates how the service is profitable for the client and prepares the benchmark for calculating profitability and accuracy. We have attached our track sheet record of the services which indicates the success ratio of the Service. The risk profile of Name Of Client indicates that he is a &laquo;High&raquo; Risk bearer client, in his investment, and the services we recommended for him match his Risk profile. The client is ready to bear all types of Risk. The client is satisfied with the Risk Profile Client is aware of the risk factor involved in the market and service. The client is agreed to all the Disclosures, Terms and conditions, and disclaimers that are mentioned on the website.</p>
<p>ASSESSMENT DONE BY STOCK BENEFITS FINANCIAL SERVICES SEBI Registered Investment Advisors Registration No. INA100007745 with Client (Proprietor STOCK BENEFITS FINANCIAL SERVICES) SEBI Registered Investment advisors Registration No. INA100007745 Disclosure Document The particulars given in this Disclosure Document have been prepared in accordance with SEBI (Investment advisors) Regulations, 2013. The purpose of the Document is to provide essential information about the Investment Advisory Services in a manner to assist and enable the prospective client/client in making an informed decision for engaging Investment Advisor before investing.</p>
<p>Descriptions about &ldquo;Investment Advisor&rdquo; History, Present business, and Background Investment Advisor is registered with SEBI as Investment Advisor with Registration No. INA100007745. The firm got its registration on 03/08/2016 and is engaged in advisory services. The focus of an Investment Advisor is to provide investment advice to the clients. Advisor aligns its interests with those of the client and seeks to provide the best-suited advice based on the client&rsquo;s risk profile. The investment Advisor first tries to understand the client&rsquo;s return expectations, risk-taking ability &amp; goals, which in turn helps to arrive at an asset allocation suitable for the client. The investment Advisor conducts frequent portfolio reviews and suggests any corrective action/s if required.</p>
<p>Terms and conditions of STOCK BENEFITS FINANCIAL SERVICES are detailed in the client agreement. Please refer to the same for details. Disciplinary history i. No penalties/directions have been issued by SEBI under the SEBI Act or Regulations made thereunder against the Investment advisor relating to Investment Advisory services. ii. There are no pending material litigations or legal proceedings, findings of inspections, or investigations for which action has been taken or initiated by any regulatory authority against the Investment advisor or its Directors, or employees. Affiliations with other intermediaries Investment Advisor has no affiliation with any other SEBI registered intermediaries. Disclosures with respect to Investment Advisor&rsquo;s own holding position in financial products/securities: Investment Advisor may hold a position in the financial products/ securities advised in its personal portfolio. Details of the same may be referred to through the disclosures made at the time of advice. Disclosures with respect to any actual or potential conflicts of interest arising from any connection to or association with any issuer of products/ securities, including any material information or facts that might compromise its objectivity or independence in the carrying on of investment advisory services. There are no actual or potential conflicts of interest arising from any connection to or association with any issuer of products/ securities, including any material information or facts that might compromise its objectivity or independence in the carrying on of investment advisory services. Such conflict of interest shall be disclosed to the client as and when they arise. Disclosure of all material facts relating to the key features of the products or securities, particularly, performance track record, warnings, disclaimers etc. Clients are requested to go through the detailed key features, performance track record of the product, or security including warnings, disclaimers, etc before investing as and when provided by the Investment Advisor. Such product materials may also be available at www.moneycontrol.com, Investing.com, www.sebi.gov.in or www.nseindia.com, or the respective issuer&rsquo;s website. Drawing client&rsquo;s attention to warnings, disclaimers in documents, and advertising materials relating to investment products. The investment Advisor draws the client&rsquo;s attention to the warnings, disclaimers in documents, and advertising materials relating to an investment product that is being recommended to the client. A brief regarding the risk associated with the investment products is available in the client agreement, same may be referred to before investing in advised products or securities. Mr. Amit Guruh Sachdeva (Proprietor STOCK BENEFITS FINANCIAL SERVICES) SEBI Registered Investment Advisor Registration No. INA100007745 (Type of Registration- Individual, Validity of Registration- Perpetual).</p>
<p><strong><u>For Client (Proprietor STOCK BENEFITS FINANCIAL SERVICES) SEBI Registered Investment advisors Registration No. INA100007745 &amp; Research Analyst No-INH100005190</u></strong></p>
<p><strong><u>Disclaimer</u></strong></p>
<ol>
<li>STOCK BENEFITS FINANCIAL SERVICES DOES NOT provide any kind of free trial of services to any client.</li>
<li>STOCK BENEFITS FINANCIAL SERVICES accepts the payments only after the successful completion of risk profiling assessment, KYC, and agreement formalities.</li>
<li>The information and views on the website &amp; all the services we provide are believed to be reliable, but we do not accept any responsibility (or liability) for errors of fact or opinion. Users have the right to choose the product/s that suit them the most.</li>
<li>Investment in equity shares has its own risks. Sincere efforts have been made to present the right investment perspective. The information contained herein is based on analysis and on sources that we consider reliable. We, however, do not vouch for the consistency or the completeness thereof. This material is for personal information and we are not responsible for any loss incurred due to it &amp; take no responsibility whatsoever for any financial profits or loss which may arise from the recommendations above.</li>
<li>Our Clients or Any third party or anyone else have no rights to forward or share our calls or SMS or Reports or Any Information Provided by us to/with anyone which is received directly or indirectly by them. If found so then Legal Actions can be taken.</li>
<li>By accessing <a href="http://www.stockbenifits.com">www.stockbenifits.com</a> or any of its associate/group sites, you have read, understood, and agree to be legally bound by the terms of the following disclaimer and user agreement.</li>
<li>STOCK BENEFITS FINANCIAL SERVICES does not guarantee the consistency, adequacy, or completeness of any information and is not responsible for any errors or omissions or for the results obtained from the use of such information.</li>
<li>STOCK BENEFITS FINANCIAL SERVICES is not responsible for any errors, omissions, or representations on any of our pages or on any links on any of our pages. <a href="http://www.stockbenifits.com">www.stockbenifits.com</a> does not endorse any way any advertisers on our web pages. Please verify the veracity of all information on your own before undertaking any alliance.</li>
<li>The information on this website is updated from time to time. <a href="http://www.stockbenifits.com">www.stockbenifits.com</a> however excludes any warranties (whether expressed or implied), as to the quality, consistency, efficacy, completeness, performance, fitness, or any of the contents of the website, including (but not limited) to any comments, feedback and advertisements contained within the Site.</li>
<li><a href="http://www.stockbenifits.com">www.stockbenifits.com</a> makes no warranty that the contents of the website are free from infection by viruses or anything else which has contaminating or destructive properties and shall have no liability in respect thereof.</li>
<li>There are risks associated with utilizing internet and short messaging system (SMS) based information and research dissemination services. Subscribers are advised to understand that the services can fail due to the failure of hardware, software, and Internet connection. While we ensure that the messages are delivered in time to the subscriber&rsquo;s Mobile Network, the delivery of these messages to the customer&rsquo;s mobile phone/handset is the responsibility of the customer&rsquo;s Mobile Network. SMS may be delayed and/or not delivered to the customer&rsquo;s mobile phone/handset on certain days, owing to technical reasons, and <a href="http://www.stockbenifits.com">www.stockbenifits.com</a> cannot be held responsible for the same.</li>
<li><a href="http://www.stockbenifits.com">www.stockbenifits.com</a> hereby expressly disclaims any implied warranties imputed by the laws of any jurisdiction. We consider ourselves and intend to be subject to the jurisdiction only of the courts of Indore in India. If you don&rsquo;t agree with any of our disclaimers above please do not read the material on any of our pages. This site is specifically for users in the territory of India. Although the access to users outside India is not denied, <a href="http://www.stockbenifits.com">www.stockbenifits.com</a> shall have no legal liabilities whatsoever in any laws of any jurisdiction other than India. We reserve the right to make changes to our site and these disclaimers, terms, and conditions at any time.</li>
<li>Stock trading is inherently risky and you agree to assume complete and full responsibility for the outcomes of all trading decisions that you make. All comments and posts made by <a href="http://www.stockbenifits.com">www.stockbenifits.com</a> is for information purposes only and under no circumstances should be used for actual trading. Under no circumstances should any person at this site make trading decisions based solely on the information discussed herein. We are qualified financial advisor and we provide all the market-based information to keep our clients informed about the real-time changes happening in the financial market, complete information provided by us consist of factual information which helps you to understand the movement of the market through the investment advice we provide. It is completely informative in nature.</li>
<li>You should strictly abide by the consultation provided by the qualified advisors at Stock Benifits Financial Services and trade only as per the levels provided by us. You agree not to make actual stock trades based on comments on the site, nor on any techniques presented or discussed on this site or any other form of information presentation. All information is for educational and informational use only. Unlike an actual performance record, simulated results do not represent actual trading. No representation is being made that any account will or is likely to achieve profits or losses similar to those shown.</li>
<li><a href="http://www.stockbenifits.com">www.stockbenifits.com</a> has a license to provide investment advice. <a href="http://www.stockbenifits.com">www.stockbenifits.com</a> is a registered investment advisor. You understand and acknowledge that there is a very high degree of risk involved in trading securities. Past results of any trader published on this website are not an indicator of future returns by that trader and are not an indicator of future returns which be realized by you.</li>
<li>Any surfing and reading of the information is the acceptance of this disclaimer. All Rights Reserved. Client (Proprietor STOCK BENEFITS FINANCIAL SERVICES) SEBI Registered Investment advisors Registration No. INA100007745 (Type of Registration- Individual, Validity of Registration- Perpetual)</li>
</ol>



</div>
</div>
</div>
</div>
</div>
</section>
</div>







<!-------------------------------------------------------------------------------------------------------------------------->






    <section class="risk-profile-form" >
        <div class="container">
            <div class="card" style="box-shadow:0px 0px 20px #0000003b">
                <div class="card-body" id="form">
                    @if (Session('error'))
                                <span style="color:red; font-weight: 600">{{ Session('error') }}</span>
                            @endif
                    <h2 class="text-center">The questionnaire for risk profiling of the client is as follows:-</h2>
                   @livewire('kyc-form')
                </div>
            </div>
        </div>
    </section>
@endsection
